apiVersion: template.openshift.io/v1
kind: Template
message: Login on https://${TENANT_NAME}-admin.${WILDCARD_DOMAIN} as ${ADMIN_USERNAME}/${ADMIN_PASSWORD}
metadata:
 annotations:
 description: 3scale API Management main system
 iconClass: icon-3scale
 openshift.io/display-name: 3scale API Management
 openshift.io/provider-display-name: Red Hat, Inc.
 tags: integration, api management, 3scale
 creationTimestamp: null
 name: 3scale-api-management
objects:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/display-name: AMP backend
    creationTimestamp: null
		labels:
